### ISSUE TITLE
update config file completion not been updated

### ISSUE THREAD

**Issue by voorjaar** [windicss/windicss-intellisense#40]
when update config file, like `windi.config.js`, completion should also been updated. And should not require reload the window.

**Comment by alexanderniebuhr** [comment]
@voorjaar we must decide here, we refactor this to allow the suggested behavior -> which might be bad for performance. Or we leave it like it is, which seems fine to me, since config files are not changed often, and it is the known behavior off vscode native setting changes. Third, we could include an auto-reload option, which just runs `Reload Window` of VScode.. what do you wish?

**Comment by voorjaar** [comment]
I wish we can hot reload with config file. I don't know if this is possible, I need to check it.

**Comment by alexanderniebuhr** [comment]
I think you might have to replace the context.subscription somehow, to change the completion items, however it is read-only and pushing a new one is not really working. So we might be able to re-activate the extension?

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss-intellisense/commit/5bfe65062d527f1ff9023ec8fdfa8af6e06f6fcb and https://github.com/windicss/windicss-intellisense/commit/e38a6e65f90a66be3abd6b6ed5c5cdc4cc2c203b fix this
