### ISSUE TITLE
Support for custom separator (for using with pug)

### ISSUE THREAD

**Issue by anhnhoktvn** [windicss/windicss-intellisense#46]
Hi, could we have a config to change the default separator `:` to something else for using with `pug`?

**Comment by alexanderniebuhr** [comment]
@anhnhoktvn which files to this includes? just `pug`

**Comment by voorjaar** [comment]
> @anhnhoktvn which files to this includes? just `pug`

No. it's a inline block.

**Comment by ThaddeusJiang** [comment]
@alexanderniebuhr OK, I will try this.

**Comment by alexanderniebuhr** [comment]
actually this is already implemented.. it just seems that `_` does not work. I have tested `/` and it works with no problem.
Since currently we do use native VS Code Trigger Characters, I think there might nothing we can change. Once we will implement the LSP it should be easy to fix

/cc @voorjaar 
escaping that character did no difference so far
https://github.com/windicss/windicss-intellisense/blob/cd248077bc30e7b2daaa3ae61afeaf2639f676f1/src/lib/completions.ts#L13
https://github.com/windicss/windicss-intellisense/blob/cd248077bc30e7b2daaa3ae61afeaf2639f676f1/src/lib/completions.ts#L80

**Comment by alexanderniebuhr** [comment]
just going to close since there was no much activity lately, if some issue still exists please reopen a new issue
